### ISSUE TITLE
Hardware Setup Image for microvisor-iot-device-demo is incorrect

### ISSUE THREAD

**Issue by graphex** [TwilioDevEd/microvisor-iot-device-demo#1]
The hardware setup image for the  microvisor-iot-device-demo shows VDD coming from the board direct to the ground rail on the breadboard, which could potentially destroy the device. The VDD and ground rails on a breadboard connect horizontally across, not vertically up and down like the middle section of the breadboard. Connecting the main power output of the board directly to ground has the potential to burn out the microvisor device since there is no resistive load to limit the current.

The red wire in the diagram below should attach from the microvisor to the same _row_ as the red wire of the breadboard, not the same _column_.
![Screen Shot 2022-11-14 at 3 42 30 PM](https://user-images.githubusercontent.com/78928/201783748-37e83c48-7de3-4c89-aea0-c7b46ee57345.png)

**Comment by smittytone** [comment]
Excellent spot! Thanks for letting me know.
